### ISSUE TITLE
Spotify/Playing a game status lacking bottom margin

### ISSUE THREAD

**Issue by Vaylentine** [Goose-Nest/GT-RevertRebrand#33]
The issue(?) persists through both version of the profile popout.
![image](https://user-images.githubusercontent.com/51290880/120278689-729ac680-c26a-11eb-8bd7-c8ee8c4fcd3b.png)
possible fix:
![image](https://user-images.githubusercontent.com/51290880/120278790-90682b80-c26a-11eb-8564-973f0fd8085f.png)

```css
/* For new popout */
.buttonsWrapper-2spIeK
{
  margin-bottom: 12px;
}

/* For optional old one */
.activity-fViXj7
{
  margin-bottom: 12px;
}
```
