### ISSUE TITLE
Revert logo top left

### ISSUE THREAD

**Issue by Frosty704** [Goose-Nest/GT-RevertRebrand#8]
![image](https://user-images.githubusercontent.com/36753686/118190479-2b5eaa00-b411-11eb-9581-48b2a04ce440.png)
they forgot to change it now they changed it pls fix this it hurts my eyes i wanna die

**Comment by Errorcrafter** [comment]
```css
/* watermark */
@font-face {
  font-family: 'Discord';
  font-weight: 700;
  src: url("https://raw.githubusercontent.com/powercord-org/powercord-backend/my-awesome-branch/web/src/assets/discord-font.otf") format("opentype");
}
.wordmark-2iDDfm:after {
  content: "Discord";
  font-size: 15px;
  position: absolute;
  width: 4000px;
  top: 5px;
  padding-left: 0px;
  font-family: 'Discord';
}
.wordmark-2iDDfm > svg {
  width: 0px;
}
```
