### ISSUE TITLE
Old colors are not applied in certain cases (overrided by Discord)

### ISSUE THREAD

**Issue by Kiki79250CoC** [Goose-Nest/GT-RevertRebrand#84]
I know it's ""semi-abandoned"", but I post this anyway, as the fix seems to be pretty simple to deploy if the dev wants to fix it one day.

---

As the title says, the old colors are not applied because they're overrided by another Discord color set.

Buttons with old color (Firefox) and new ones:
![image](https://user-images.githubusercontent.com/54137141/187071043-1707d181-2159-4566-99b1-c2b2edf53340.png)

View of the values when "Leave server" button text is selected in devtool:
![image](https://user-images.githubusercontent.com/54137141/187070942-ced6c28a-daf4-4596-8673-de954cfbf872.png)

The only workaround I see for the moment is to use that awful "!important" marker on the incrimined lines.

For the "Invite" button, I'm not sure if this is because i'm familiarized with the "new" color without remarking it, so maybe this issue is not valid for the "Blurple" colors set.

**Comment by Kiki79250CoC** [comment]
The workaround:
```css
.theme-dark, .theme-light {
  /* Revert new green to old color */
  --info-positive-foreground: var(--old-green);
  --status-positive-background: var(--old-green);
  --text-positive: var(--old-green);

  /* Revert new red to old color */
  --text-danger: var(--old-red);
  --info-danger-foreground: var(--old-red);
  --status-danger-background: var(--old-red);
}
.colorDanger-3n-KnP.focused-3qFvc8 {
    background-color: var(--old-red);
    color: #ffffff;
}
```
